# Generated by Django 3.0.7 on 2021-02-06 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('starred', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckbookMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('role', models.TextField(choices=[('ON', 'OWNER'), ('OB', 'OBSERVER'), ('ED', 'EDITOR')], max_length=2)),
                ('checkbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Checkbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkbook_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
