# Generated by Django 3.0.7 on 2021-02-07 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0002_auto_20210207_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbookmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkbook_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
