# Generated by Django 3.0.7 on 2021-02-08 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_auto_20210207_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbook',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'length of characters is too small')]),
        ),
    ]
