# Generated by Django 3.1.6 on 2021-02-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_auto_20210208_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='value')),
                ('checkbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='paper.checkbook')),
            ],
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('checkbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='paper.checkbook')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('checkbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='paper.checkbook')),
            ],
        ),
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=60)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='paper.checklistitem')),
            ],
        ),
        migrations.CreateModel(
            name='AudioItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('audio', models.FileField(upload_to='uploads/notes/')),
                ('title', models.CharField(max_length=20)),
                ('checkbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voicenotes', to='paper.checkbook')),
            ],
        ),
    ]
