# Generated by Django 3.1.6 on 2021-02-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_audioitem_checkitem_checklistitem_imageitem_textitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='title',
            field=models.CharField(default='Title', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageitem',
            name='title',
            field=models.CharField(default='Title', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textitem',
            name='title',
            field=models.CharField(default='Title', max_length=20),
            preserve_default=False,
        ),
    ]
